update_fastlane

default_platform(:android)

platform :android do
    lane :alpha do
      gradle(
        task: 'assemble',
        build_type: 'Release'
      )
      upload_to_play_store(
        track: 'alpha',
        apk: './app/build/outputs/apk/release/app-release.apk'
      )
    end
    lane :beta do
        gradle(
            task: 'assemble',
            build_type: 'Release'
        )
        upload_to_play_store(
            track: 'beta',
            apk: './app/build/outputs/apk/release/app-release.apk'
        )
    end
end
